"""Hopefully fixed relationships of parent child

Revision ID: 2aff82e211ef
Revises: e7b610917c4e
Create Date: 2025-04-09 16:15:38.975202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aff82e211ef'
down_revision = 'e7b610917c4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], name=op.f('fk_appointments_child_id_children')),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('fk_appointments_doctor_id_doctors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments'))
    )
    op.drop_table('appointment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('child_id', sa.INTEGER(), nullable=False),
    sa.Column('doctor_id', sa.INTEGER(), nullable=False),
    sa.Column('start_time', sa.DATETIME(), nullable=False),
    sa.Column('end_time', sa.DATETIME(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], name='fk_appointment_child_id_children'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name='fk_appointment_doctor_id_doctors'),
    sa.PrimaryKeyConstraint('id', name='pk_appointment')
    )
    op.drop_table('appointments')
    # ### end Alembic commands ###
