"""edit doctor model

Revision ID: 589fcc918217
Revises: ee60eabbab7a
Create Date: 2025-04-10 10:21:32.936312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '589fcc918217'
down_revision = 'ee60eabbab7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_column('specialty')
        batch_op.drop_column('age_of_care')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age_of_care', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('specialty', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
