"""Add year_experience to doctors

Revision ID: 9547a194bba2
Revises: c097da4039cf
Create Date: 2025-04-14 12:15:01.018930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9547a194bba2'
down_revision = 'c097da4039cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_experience', sa.Integer(), nullable=True))
        batch_op.drop_column('years_experience')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('years_experience', sa.INTEGER(), nullable=True))
        batch_op.drop_column('year_experience')

    # ### end Alembic commands ###
