"""Adjust relationships, take 25...

Revision ID: ee60eabbab7a
Revises: 2aff82e211ef
Create Date: 2025-04-10 08:29:24.591848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee60eabbab7a'
down_revision = '2aff82e211ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.drop_column('appointment')

    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_parents_child_id_children', type_='foreignkey')
        batch_op.drop_column('child_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('child_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_parents_child_id_children', 'children', ['child_id'], ['id'])

    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
